// frontend/src/lib/components/HistoryTable.svelte
<script lang="ts">
	import firstImg from '$lib/assets/icons/first.svg';
	import lastImg from '$lib/assets/icons/last.svg';
	import nextImg from '$lib/assets/icons/next.svg';
	import previousImg from '$lib/assets/icons/previous.svg';
	const { setActiveIndex, activeIndex, moveHistory, highlightLastArrow } = $props();
	const moveButtons: (HTMLButtonElement | null)[] = $state([]);
	$effect(() => {
		const activeButton = moveButtons[activeIndex];
		activeButton?.scrollIntoView({ behavior: 'smooth', block: 'end' });
	});
</script>

<div class="w-full bg-gray-800 text-sm md:w-[300px] md:text-lg">
	<div class="flex w-full items-center justify-between bg-[#232327] px-5 md:px-2">
		{#if moveHistory.length > 0}
			<div class="flex gap-[10px]">
				<button
					aria-label="go to first move"
					class="flex cursor-pointer items-center justify-center py-1 hover:bg-gray-700"
					onclick={() => {
						setActiveIndex(-1);
					}}
				>
					<img src={firstImg} alt="go to first move" class="h-[16px] md:h-[24px]" />
				</button>
				<button
					aria-label="go to previous move"
					class="flex cursor-pointer items-center justify-center py-1 hover:bg-gray-700"
					onclick={() => {
						setActiveIndex(activeIndex - 1);
					}}
					><img src={previousImg} class="h-[16px] md:h-[24px]" alt="go to previous move" /></button
				>
			</div>
			<div class="flex gap-[10px]">
				<button
					aria-label="go to next move"
					class="flex cursor-pointer items-center justify-center py-1 hover:bg-gray-700"
					onclick={() => {
						setActiveIndex(activeIndex + 1);
					}}><img src={nextImg} alt="go to next move" class="h-[16px] md:h-[24px]" /></button
				>
				<button
					aria-label="go to latest move"
					class={`flex cursor-pointer items-center justify-center py-1 hover:bg-gray-700 ${highlightLastArrow && 'animate-pulse bg-blue-700'}`}
					onclick={() => {
						setActiveIndex(moveHistory.length - 1);
					}}
				>
					<img src={lastImg} alt="go to last move" class="h-[16px] md:h-[24px]" />
				</button>
			</div>
		{/if}
	</div>
	<div
		class="grid h-[50px] grid-cols-[1fr_5fr_5fr] place-items-center overflow-y-auto px-2 py-2 md:h-[70px] md:overflow-x-hidden"
	>
		{#each moveHistory as move, index}
			{#if index % 2 == 0}
				<span>{index / 2 + 1}.</span>
			{/if}
			<button
				bind:this={moveButtons[index]}
				onclick={() => {
					setActiveIndex(index);
				}}
				class={`h-fit w-fit cursor-pointer px-1 md:px-3 ${activeIndex == index ? 'bg-gray-700' : ''}`}
			>
				{move.MoveNotation}
			</button>
		{/each}
	</div>
</div>

<style>
</style>

// frontend/src/components/HistoryTable.tsx
import useChessStore from "../store/gameStore.ts";
import { useRef, useEffect, Fragment } from "react";
import { FastForward, Rewind } from "@phosphor-icons/react";

export default function HistoryTable({ history }: { history: any }) {
  const {
    setGroundFen,
    setGroundLastMoves,
    setGroundViewOnly,
    board,
    activeIndex,
    setActiveIndex,
  } = useChessStore();
  const moveRefs = useRef<(HTMLButtonElement | null)[]>([]); // Store refs for each move

  // Scroll to active move when activeIndex or active12 changes
  useEffect(() => {
    const activeButton = moveRefs.current[activeIndex]; // Find the right button
    activeButton?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [activeIndex]);

  return (
    <div className="h-[310px] text-lg px-4 py-2  bg-gray-800 relative">
      <div className="overflow-y-auto h-[250px] overflow-x-hidden w-full grid grid-cols-[1fr_16fr_16fr] content-start place-items-center">
        {history &&
          history.map((move, index) => {
            let x;
            if (index % 2 == 0) x = <span>{index / 2 + 1}.</span>;
            return (
              <Fragment key={index}>
                {x}
                <button
                  ref={(el) => (moveRefs.current[index] = el)}
                  onClick={() => {
                    setGroundFen(move.MoveFen);
                    setGroundLastMoves(move.Orig, move.Dest);
                    if (index === history.length - 1) {
                      setGroundViewOnly(false);
                    } else {
                      setGroundViewOnly(true);
                    }
                    setActiveIndex(index);
                  }}
                  className={`cursor-pointer h-fit w-fit px-4 py-2 ${activeIndex == index ? "bg-gray-700" : ""}`}
                >
                  {move.MoveNotation}
                </button>
              </Fragment>
            );
          })}
      </div>
      {history && (
        <div className="absolute bottom-2 w-4/5 flex justify-around">
          <button
            className="cursor-pointer w-1/3 flex justify-center items-center hover:bg-gray-700"
            onClick={() => {
              setGroundFen(history[0].MoveFen);
              setGroundLastMoves(history[0].Orig, history[0].Dest);
              setGroundViewOnly(true);
              setActiveIndex(0);
            }}
          >
            <Rewind size={32} />
          </button>
          <button
            className="cursor-pointer w-1/3 flex justify-center items-center hover:bg-gray-700"
            onClick={() => {
              setGroundFen(board.fen());
              setGroundLastMoves(
                history[history.length - 1].Orig,
                history[history.length - 1].Dest,
              );
              setActiveIndex(history.length - 1);

              setGroundViewOnly(false);
            }}
          >
            <FastForward size={32} />
          </button>
        </div>
      )}
    </div>
  );
}
