// frontend/src/pages/Play.tsx
import { useNavigate } from "react-router";
import useWebSocketStore from "../store/socketStore";
import { useEffect } from "react";
import { getBaseURL } from "../utils/urlUtils";
import useAuthStore from "../store/authStore";

export default function Play() {
  const { connect } = useWebSocketStore();
  const { setNavigate } = useWebSocketStore();
  const navigate = useNavigate();
  const user = useAuthStore((state) => state.user);

  useEffect(() => {
    setNavigate(navigate);
    connect();
  }, [connect, navigate, setNavigate]);

  async function handleInitGame(timerCode: number) {
    await fetch(`${getBaseURL()}/game/init`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ username: user?.username, timerCode }),
    });
  }
  // useEffect(() => {
  //
  //   handleInitGame();
  // }, [user]);
  //
  return (
    <div className="w-full h-[500px] flex gap-5 items-center justify-center">
      <button
        onClick={() => handleInitGame(2)}
        className="w-[150px] h-[100px] bg-gray-400 cursor-pointer text-xl"
      >
        3+2
      </button>
      <button
        onClick={() => handleInitGame(3)}
        className="w-[150px] h-[100px] bg-gray-400 cursor-pointer text-xl"
      >
        10+0
      </button>
      <button
        onClick={() => handleInitGame(1)}
        className="w-[150px] h-[100px] bg-gray-400 cursor-pointer text-xl"
      >
        1+0
      </button>
    </div>
  );
}

// frontend-svelte/src/routes/play/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { getBaseURL } from '$lib/utils';

	const { data } = $props();

	if (!data.user) goto('/');

	async function handleInitGame(timerCode: number) {
		await fetch(`${getBaseURL()}/game/init`, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			credentials: 'include',
			body: JSON.stringify({ username: data.user?.username, timerCode })
		});
	}
</script>

<div class="flex h-[500px] w-full items-center justify-center gap-5">
	<button
		onclick={() => handleInitGame(2)}
		class="h-[100px] w-[150px] cursor-pointer bg-gray-400 text-xl"
	>
		3+2
	</button>
	<button
		onclick={() => handleInitGame(3)}
		class="h-[100px] w-[150px] cursor-pointer bg-gray-400 text-xl"
	>
		10+0
	</button>
	<button
		onclick={() => handleInitGame(1)}
		class="h-[100px] w-[150px] cursor-pointer bg-gray-400 text-xl"
	>
		1+0
	</button>
</div>
