// frontend/src/components/Chat.tsx
import { useEffect, useRef, useState } from "react";
import useWebSocketStore from "../store/socketStore";
import useAuthStore from "../store/authStore";
import useChessStore from "../store/gameStore";
import useChatStore from "../store/chatStore";

export default function Chat({ gameID }: { gameID: string }) {
  const { sendMessage } = useWebSocketStore();
  const { messages } = useChatStore();
  const { user } = useAuthStore();
  const { whiteID, blackID, whiteusername, blackusername } = useChessStore();
  const [input, setInput] = useState("");

  const endRef = useRef<null | HTMLDivElement>(null);

  const scrollToBottom = () => {
    endRef.current?.scrollIntoView({
      behavior: "smooth",
    });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSendMessage = () => {
    if (input.trim() !== "") {
      sendMessage({
        type: "chat",
        payload: {
          sender: Number(user?.userID),
          receiver: Number(user?.userID === whiteID ? blackID : whiteID),
          senderUsername: user?.username,
          receiverUsername:
            user?.username === whiteusername ? blackusername : whiteusername,
          text: input,
          gameID: Number(gameID),
        },
      });
      setInput("");
    }
  };

  return (
    <div className="p-4 border rounded shadow-lg">
      <div className="h-64 overflow-y-auto border-b mb-2 p-2 text-lg">
        {messages.map((msg, index) => {
          if (msg.gameID == gameID) {
            return (
              <div key={index} className="mb-1">
                <strong>{msg.sender}:</strong> {msg.text}
              </div>
            );
          }
        })}
        <div ref={endRef}></div>
      </div>
      <div className="flex gap-2 w-full text-sm">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          className="border p-2 flex-1 rounded"
          placeholder="Type a message..."
        />
        <button
          onClick={handleSendMessage}
          className="bg-blue-500 text-white px-4 py-2 rounded"
        >
          Send
        </button>
      </div>
    </div>
  );
}

// frontend/src/lib/components/Chat.svelte
<script lang="ts">
	import { websocketStore } from '$lib/websocket';
	import { onDestroy, onMount } from 'svelte';
	interface MessageInterface {
		sender: string;
		receiver: string;
		text: string;
		gameID: number;
	}
	let messages: MessageInterface[] = $state([]);
	const { username, userID, gameID, whiteID, blackID, whiteUsername, blackUsername } = $props();
	let text = $state('');

	const scrollToBottom = (node: HTMLDivElement, watch: () => MessageInterface[]) => {
		$effect(() => {
			void watch?.();
			node.scrollIntoView({
				behavior: 'smooth'
			});
		});
	};

	const handleSend = () => {
		if (text.trim() != '') {
			websocketStore.sendMessage({
				type: 'chat',
				payload: {
					sender: userID,
					receiver: userID === whiteID ? blackID : whiteID,
					senderUsername: username,
					receiverUsername: username === whiteUsername ? blackUsername : whiteUsername,
					text,
					gameID
				}
			});
			text = '';
		}
	};

	const handleMessage = (payload: any) => {
		if (payload.gameID != gameID) return;
		if (messages) messages = [...messages, payload];
		else messages = [payload];
	};

	onMount(() => {
		websocketStore.onMessage('chat', handleMessage);
	});
	onDestroy(() => {
		websocketStore.offMessage('chat', handleMessage);
	});
</script>

<div class="w-full rounded bg-[#1c1d1e] p-4 shadow-lg">
	<div class="mb-2 h-64 overflow-y-auto border-b p-2 text-lg">
		{#each messages as msg}
			{#if msg.gameID == gameID}
				<div class="mb-1">
					<strong>{msg.sender}:</strong>
					{msg.text}
				</div>
			{/if}
		{/each}
		<div use:scrollToBottom={() => messages}></div>
	</div>
	<div class="flex gap-2 text-sm">
		<input
			type="text"
			bind:value={text}
			class="flex-1 rounded border p-2"
			placeholder="Type a message..."
		/>
		<button onclick={handleSend} class="rounded bg-blue-500 px-4 py-2 text-white"> Send </button>
	</div>
</div>
