// frontend/src/pages/SetUsername.tsx
import {useState} from "react";
import {getBaseURL} from "../utils/urlUtils.ts";

export default function SetUsername() {
    const [username, setUsername] = useState("");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");

    const handleSubmit = async () => {
setLoading(true);

    const res = await fetch(`${getBaseURL()}/set-username`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username}),
        credentials: "include"
    });

    const response = await res.json();

    if (!res.ok) {
        setLoading(false);
        setError(response.error);
        return;
    }

    window.location.href="/";

    }

    return <div className="flex flex-col items-center justify-center mt-10 gap-4 p-6 bg-gray-100 rounded-lg shadow-md">
        <input
            type="text"
            placeholder="Enter your username"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent"
        />

        {error && <p className="text-red-500 text-sm">{error}</p>}

        <button
            className="w-[200px] bg-blue-500 text-white py-2 rounded-md hover:bg-blue-600 transition-all disabled:bg-gray-400 disabled:cursor-not-allowed"
            onClick={handleSubmit}
            disabled={loading}
        >
            {loading ? "Submitting..." : "Submit"}
        </button>
    </div>
}

// frontend/src/routes/set-username/+page.svelte
<script>
	import { getBaseURL } from '$lib/utils';

	let username = $state('');
	let loading = $state(false);
	let error = $state('');

	const handleSubmit = async () => {
		loading = true;

		const res = await fetch(`${getBaseURL()}/set-username`, {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({ username }),
			credentials: 'include'
		});

		const response = await res.json();

		if (!res.ok) {
			loading = false;
			error = response.error;
			return;
		}

		window.location.href = '/';
	};
</script>

<svelte:head>
	<title>Set your mcc username</title>
</svelte:head>
<div class="mt-10 flex flex-col items-center justify-center gap-4 rounded-lg p-6">
	<input
		type="text"
		placeholder="Enter your username"
		bind:value={username}
		class="rounded-md border border-gray-300 bg-gray-100 px-4 py-2 text-black focus:border-transparent focus:ring-2 focus:ring-blue-400 focus:outline-none"
	/>

	{#if error}
		<p class="text-sm text-red-500">{error}</p>
	{/if}
	<button
		class="w-[200px] rounded-md bg-blue-500 py-2 text-white transition-all hover:bg-blue-600 disabled:cursor-not-allowed disabled:bg-gray-400"
		onclick={handleSubmit}
		disabled={loading}
	>
		{loading ? 'Submitting...' : 'Submit'}
	</button>
</div>
